services:
  - type: web
    name: hr-pro-attendance
    env: node
    plan: free
    buildCommand: "yarn && yarn build"
    startCommand: "yarn start"
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: API_KEY
        sync: false # User sẽ điền API Key vào Render Dashboard
